name: 'octofetch'
description: ''

inputs:
  github_token:
    description: 'GitHub token for authentication.'
    required: true
  config_file:
    description: 'Path to the configuration file.'
    required: false

runs:
  using: 'composite'
  steps:
    - name: 'Setup Bun Runtime'
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: 'Execute'
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: 
        bun run ${{ github.action_path }}/index.ts
      shell: bash

author: '@riteshraj-shetage'
