name: "octofetch"
description: "A declarative, lightweight GitHub GraphQL action that executes raw .gql telemetry queries."
author: "@riteshraj-shetage"

branding:
  icon: "zap"
  color: "gray-dark"

inputs:
  github_token:
    description: "GitHub token for authentication."
    required: true
  query_file:
    description: "Path to the .gql query file."
    required: true
  variables:
    description: "JSON string containing query variables."
    required: false
    default: "{}"
  output_file:
    description: "Path to save the JSON payload."
    required: false
    default: "./data/sourced.json"

runs:
  using: "composite"
  steps:
    - name: "Setup Bun Runtime"
      uses: oven-sh/setup-bun@v1

    - name: "Execute Action"
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        QUERY_FILE: ${{ inputs.query_file }}
        VARIABLES: ${{ inputs.variables }}
        OUTPUT_FILE: ${{ inputs.output_file }}
      run: |
        echo "::: Running octofetch :::"
        set -e

        if [ -z "$GITHUB_TOKEN" ]; then
          echo "::error:: GITHUB_TOKEN is missing or empty."
          exit 1
        fi

        if [ ! -f "$QUERY_FILE" ]; then
          echo "::error:: Query file not found at: $QUERY_FILE"
          exit 1
        fi

        bun run ${{ github.action_path }}/index.ts
      shell: bash